/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    topics: Topic;
    modules: Module;
    lessons: Lesson;
    'story-themes': StoryTheme;
    books: Book;
    chapters: Chapter;
    'chat-themes': ChatTheme;
    chats: Chat;
    'wallet-transactions': WalletTransaction;
    purchases: Purchase;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    topics: TopicsSelect<false> | TopicsSelect<true>;
    modules: ModulesSelect<false> | ModulesSelect<true>;
    lessons: LessonsSelect<false> | LessonsSelect<true>;
    'story-themes': StoryThemesSelect<false> | StoryThemesSelect<true>;
    books: BooksSelect<false> | BooksSelect<true>;
    chapters: ChaptersSelect<false> | ChaptersSelect<true>;
    'chat-themes': ChatThemesSelect<false> | ChatThemesSelect<true>;
    chats: ChatsSelect<false> | ChatsSelect<true>;
    'wallet-transactions': WalletTransactionsSelect<false> | WalletTransactionsSelect<true>;
    purchases: PurchasesSelect<false> | PurchasesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  /**
   * In ₹. Only ever changed by server-side wallet logic — never edit by hand except for support fixes.
   */
  walletBalance?: number | null;
  streakDays?: number | null;
  /**
   * Topics where the paid bundle has been purchased
   */
  unlockedTopics?: (number | Topic)[] | null;
  unlockedBooks?: (number | Book)[] | null;
  /**
   * One row per lesson the user has opened/completed
   */
  lessonProgress?:
    | {
        lesson: number | Lesson;
        completed?: boolean | null;
        lastOpenedAt?: string | null;
        id?: string | null;
      }[]
    | null;
  savedItems?:
    | {
        itemType?: ('lesson' | 'book' | 'chat') | null;
        lesson?: (number | null) | Lesson;
        book?: (number | null) | Book;
        chat?: (number | null) | Chat;
        id?: string | null;
      }[]
    | null;
  /**
   * Preferences only for now — no email/push sending is wired up yet, this just stores what the user wants.
   */
  notificationPrefs?: {
    dailyReminder?: boolean | null;
    weeklyDigest?: boolean | null;
    newChapterAlerts?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * The big cards on Home → Popular Topics, and the Learn page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "topics".
 */
export interface Topic {
  id: number;
  title: string;
  /**
   * Used in the URL, e.g. talking-in-school
   */
  slug: string;
  /**
   * Shown on the topic card and hero, e.g. "Find your voice with classmates, teachers, and new friends..."
   */
  shortDescription: string;
  /**
   * Icon shown on the topic card
   */
  icon: 'users' | 'graduation-cap' | 'heart' | 'briefcase' | 'mic' | 'message-circle' | 'book' | 'sparkles';
  /**
   * Pastel background for the topic card, matched to the Figma palette
   */
  cardColor: 'peach' | 'mint' | 'pink' | 'blue' | 'lavender' | 'butter';
  /**
   * Lower numbers show first
   */
  order?: number | null;
  featured?: boolean | null;
  /**
   * How many lessons (counted across the whole topic, in order) are free. E.g. 3 — matches "3 Free" badge on the homepage.
   */
  freeLessonCount: number;
  /**
   * Price in ₹ (wallet credits) to unlock ALL remaining lessons in this topic, as one bundle.
   */
  unlockPrice: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * A single story/book within a theme.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "books".
 */
export interface Book {
  id: number;
  theme: number | StoryTheme;
  title: string;
  slug: string;
  blurb: string;
  cover?: (number | null) | Media;
  /**
   * "Weekly" shows a countdown to the next chapter, like a serialized story.
   */
  releaseSchedule: 'all-at-once' | 'weekly';
  /**
   * First N chapters free, e.g. 2.
   */
  freeChapterCount: number;
  /**
   * Price in ₹ to unlock the rest of the book.
   */
  unlockPrice: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * Romance, Suspense, Mystery, Emotional, etc.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "story-themes".
 */
export interface StoryTheme {
  id: number;
  title: string;
  slug: string;
  description?: string | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * One lesson screen. Content is built from blocks you add/remove/reorder freely.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lessons".
 */
export interface Lesson {
  id: number;
  module: number | Module;
  title: string;
  slug: string;
  /**
   * Shown as "5 min read"
   */
  estimatedMinutes: number;
  /**
   * Position within the module (1, 2, 3, 4...)
   */
  orderInModule: number;
  /**
   * Position across the WHOLE topic, counting every lesson in every module in order. This is what decides free-vs-paid: compare against the Topic's "Free lesson count". Lesson 1-3 across the topic = free, exactly like the homepage "3 Free" badge.
   */
  orderInTopic: number;
  /**
   * Add, remove, and drag to reorder sections. Matches Introduction / Learn Concept / See the Difference / Real Conversations / Media / Practice / Try This Today / Key Takeaways from your Figma.
   */
  content?:
    | (
        | {
            body: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'intro';
          }
        | {
            heading: string;
            body: string;
            points?:
              | {
                  title?: string | null;
                  body?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'concept';
          }
        | {
            lessEffectiveLabel?: string | null;
            lessEffectiveText: string;
            moreEffectiveLabel?: string | null;
            moreEffectiveText: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'comparison';
          }
        | {
            heading?: string | null;
            messages?:
              | {
                  text: string;
                  sender: 'other' | 'self';
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'realConversation';
          }
        | {
            mediaType: 'audio' | 'video';
            file: number | Media;
            caption?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'mediaEmbed';
          }
        | {
            prompt: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'practice';
          }
        | {
            body: string;
            buttonLabel?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'tryToday';
          }
        | {
            items?:
              | {
                  text: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'takeaways';
          }
      )[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Sits inside a Topic. E.g. "Breaking the Ice" inside "Talking in School".
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "modules".
 */
export interface Module {
  id: number;
  topic: number | Topic;
  title: string;
  slug: string;
  shortDescription?: string | null;
  /**
   * Position within the topic — controls the 1, 2, 3, 4 numbering shown on the Topic page
   */
  order: number;
  /**
   * Sequential = must finish previous module to open this one (as shown in the mockup with "Locked" tags). Open = always accessible.
   */
  unlockRule: 'sequential' | 'open';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "chats".
 */
export interface Chat {
  id: number;
  theme: number | ChatTheme;
  /**
   * e.g. "Taking things from casual to serious"
   */
  title: string;
  messages?:
    | {
        text: string;
        sender: 'other' | 'self';
        /**
         * e.g. "7:14 PM" — cosmetic only
         */
        timestamp?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Uncheck to make this a paid sample chat
   */
  free?: boolean | null;
  /**
   * Optional — lets this chat appear inside a related Lesson's "Real Conversations" block as a "Read the full chat" link
   */
  linkedLesson?: (number | null) | Lesson;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "chat-themes".
 */
export interface ChatTheme {
  id: number;
  title: string;
  slug: string;
  /**
   * Icon shown next to the theme name
   */
  icon?: ('heart' | 'graduation-cap' | 'users' | 'message-circle' | 'briefcase' | 'home') | null;
  /**
   * Left-border/accent color for this theme, matched to the Figma chat library screen
   */
  color?: ('pink' | 'blue' | 'green' | 'yellow' | 'purple' | 'orange') | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "chapters".
 */
export interface Chapter {
  id: number;
  book: number | Book;
  title: string;
  /**
   * e.g. chapter-3
   */
  slug: string;
  orderInBook: number;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * For weekly releases — chapter stays hidden until this date/time, set by you in advance.
   */
  publishAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "wallet-transactions".
 */
export interface WalletTransaction {
  id: number;
  user: number | User;
  type: 'topup' | 'spend' | 'refund';
  /**
   * In ₹. Positive for top-up/refund, negative for spend.
   */
  amount: number;
  /**
   * Set only for topup rows
   */
  razorpayPaymentId?: string | null;
  /**
   * e.g. "Unlocked Talking in School bundle"
   */
  note?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "purchases".
 */
export interface Purchase {
  id: number;
  user: number | User;
  itemType: 'topic' | 'book';
  topic?: (number | null) | Topic;
  book?: (number | null) | Book;
  pricePaid: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'topics';
        value: number | Topic;
      } | null)
    | ({
        relationTo: 'modules';
        value: number | Module;
      } | null)
    | ({
        relationTo: 'lessons';
        value: number | Lesson;
      } | null)
    | ({
        relationTo: 'story-themes';
        value: number | StoryTheme;
      } | null)
    | ({
        relationTo: 'books';
        value: number | Book;
      } | null)
    | ({
        relationTo: 'chapters';
        value: number | Chapter;
      } | null)
    | ({
        relationTo: 'chat-themes';
        value: number | ChatTheme;
      } | null)
    | ({
        relationTo: 'chats';
        value: number | Chat;
      } | null)
    | ({
        relationTo: 'wallet-transactions';
        value: number | WalletTransaction;
      } | null)
    | ({
        relationTo: 'purchases';
        value: number | Purchase;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  walletBalance?: T;
  streakDays?: T;
  unlockedTopics?: T;
  unlockedBooks?: T;
  lessonProgress?:
    | T
    | {
        lesson?: T;
        completed?: T;
        lastOpenedAt?: T;
        id?: T;
      };
  savedItems?:
    | T
    | {
        itemType?: T;
        lesson?: T;
        book?: T;
        chat?: T;
        id?: T;
      };
  notificationPrefs?:
    | T
    | {
        dailyReminder?: T;
        weeklyDigest?: T;
        newChapterAlerts?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "topics_select".
 */
export interface TopicsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  shortDescription?: T;
  icon?: T;
  cardColor?: T;
  order?: T;
  featured?: T;
  freeLessonCount?: T;
  unlockPrice?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "modules_select".
 */
export interface ModulesSelect<T extends boolean = true> {
  topic?: T;
  title?: T;
  slug?: T;
  shortDescription?: T;
  order?: T;
  unlockRule?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lessons_select".
 */
export interface LessonsSelect<T extends boolean = true> {
  module?: T;
  title?: T;
  slug?: T;
  estimatedMinutes?: T;
  orderInModule?: T;
  orderInTopic?: T;
  content?:
    | T
    | {
        intro?:
          | T
          | {
              body?: T;
              id?: T;
              blockName?: T;
            };
        concept?:
          | T
          | {
              heading?: T;
              body?: T;
              points?:
                | T
                | {
                    title?: T;
                    body?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        comparison?:
          | T
          | {
              lessEffectiveLabel?: T;
              lessEffectiveText?: T;
              moreEffectiveLabel?: T;
              moreEffectiveText?: T;
              id?: T;
              blockName?: T;
            };
        realConversation?:
          | T
          | {
              heading?: T;
              messages?:
                | T
                | {
                    text?: T;
                    sender?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        mediaEmbed?:
          | T
          | {
              mediaType?: T;
              file?: T;
              caption?: T;
              id?: T;
              blockName?: T;
            };
        practice?:
          | T
          | {
              prompt?: T;
              id?: T;
              blockName?: T;
            };
        tryToday?:
          | T
          | {
              body?: T;
              buttonLabel?: T;
              id?: T;
              blockName?: T;
            };
        takeaways?:
          | T
          | {
              items?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "story-themes_select".
 */
export interface StoryThemesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "books_select".
 */
export interface BooksSelect<T extends boolean = true> {
  theme?: T;
  title?: T;
  slug?: T;
  blurb?: T;
  cover?: T;
  releaseSchedule?: T;
  freeChapterCount?: T;
  unlockPrice?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "chapters_select".
 */
export interface ChaptersSelect<T extends boolean = true> {
  book?: T;
  title?: T;
  slug?: T;
  orderInBook?: T;
  body?: T;
  publishAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "chat-themes_select".
 */
export interface ChatThemesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  icon?: T;
  color?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "chats_select".
 */
export interface ChatsSelect<T extends boolean = true> {
  theme?: T;
  title?: T;
  messages?:
    | T
    | {
        text?: T;
        sender?: T;
        timestamp?: T;
        id?: T;
      };
  free?: T;
  linkedLesson?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "wallet-transactions_select".
 */
export interface WalletTransactionsSelect<T extends boolean = true> {
  user?: T;
  type?: T;
  amount?: T;
  razorpayPaymentId?: T;
  note?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "purchases_select".
 */
export interface PurchasesSelect<T extends boolean = true> {
  user?: T;
  itemType?: T;
  topic?: T;
  book?: T;
  pricePaid?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}